name: Lint and Test

on: [push]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pre-commit install

    - name: Pre-Commit
      run: pre-commit run --all-files
