name: Code Quality

on: [push]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
      - uses: actions/setup-python@v2
        with:
            python-version: 3.11
      - run: pip install pylint

  black:
    name: Black
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - uses: psf/black@stable
      with:
        options: "--check --verbose"
        version: "~= 22.0"

  pylint:
      name: Pylint
      runs-on: ubuntu-latest
      needs: setup

      steps:
        - run: pylint **/*.py --error-only --reports y

  # pullrequests:
  #   name: Name Check
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v2
